### ISSUE TITLE
Remove temporary file when vlc exits?

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#10]
When exiting vlc after playing a torrent, the .parts file is left on disk.  Perhaps it is better to remove it when vlc exits, to avoid filling up the disk with temp files?

**Comment by johang** [comment]
I think you can add something like this to the destructor of the Download class:

```
#if LIBTORRENT_VERSION_NUM < 10200
	int flags = 0;
#else
	libtorrent::remove_flags_t flags = {};
#endif

	flags |= libtorrent::session::delete_files;

	m_session->remove_torrent(m_handle, flags);
```

btfs has something similar.
