### ISSUE TITLE
Anything to learn from alternative implementation?

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#11]
Hi.  A while back, I was told that the author of https://github.com/tguillem/vlc/compare/tr would get in touch with you.  Did he?  Did you check out the code to see if there is anything to learn from it to improve this plugin?

**Comment by johang** [comment]
Haven't talked to him, but still open for collaboration :-)

**Comment by marataziat** [comment]
You can install it via ```sudo apt install vlc-plugin-bittorrent``` :)

**Comment by petterreinholdtsen** [comment]
Hm, the 'tr' branch from tguillem is gone.  Anyone know what happened to it?

**Comment by marataziat** [comment]
We should add instructions that users can simply download and install vlc-bittorent via apt on the README!

**Comment by johang** [comment]
I just update README with this. Thanks for pointing that out.

**Comment by marataziat** [comment]
Any way to use this on windows? I don't want to download windows SDK and compile it by myself :)
