### ISSUE TITLE
VLC refuses to exit when asked to stop

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#13]
When playing a torrent stream, for example https://archive.org/download/LoveNest/LoveNest_archive.torrent, VLC refuses to exit when asked to stop before the video playback have started.

**Comment by johang** [comment]
This is probably because Download::read() is uninterruptible.

**Comment by petterreinholdtsen** [comment]
Right.  Combined with issue #9, this make it hard to reliably get a video stream going.  vlc refuses to stop when nothing happen, and I need to run vlc several times before the video will start. :(
