### ISSUE TITLE
Incorrect version number in configure.ac

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#18]
The AC_INIT() macro in configure.ac lists the version as 2.1, while the git tag is 2.2.  Did you forget to update it when making the 2.2 release?

**Comment by johang** [comment]
Yeah, I forget to update that. I repushed master and the tag an hour ago. So now it's correct.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> Yeah, I forget to update that. I repushed master and the tag an hour
> ago. So now it's correct.

Moving/renaming tags only creates hassle and do not really work when
several people have cloned a repository.  My clone have the old tag, and
there is no automatic way to get the moved tag.  Besides, the version
tag is already set in the Debian repository and there is no use trying
to move it.  The only way forward for me is to wait for the next release
with a new tag name.

Rewriting git history like this only work flawlessly on local git
repositories never shared with anyone.

-- 
Happy hacking
Petter Reinholdtsen
