### ISSUE TITLE
Seeking in video do not work.

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#2]
When trying to play a movie from archive.org, for example https://archive.org/download/LoveNest/LoveNest_archive.torrent, it is impossible to change the video position (aka seeking).

**Comment by johang** [comment]
Does it happen all the time? What if you restart vlc (i.e. recreate the whole swarm)? Bittorrent is designed as a streaming/realtime protocol, so using it as such is a bit awkward.

This project is actually a spin-off off a different project of mine (https://github.com/johang/btfs). vlc-bittorrent and btfs is diverged lately. I have made a few fixes to improve stream stability in btfs that haven't reached vlc-bittorrent.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> Does it happen all the time? What if you restart vlc (i.e. recreate
> the whole swarm)? Bittorrent is designed as a streaming/realtime
> protocol, so using it as such is a bit awkward.

Every time I tried to seek i the video so far, it would start from the
beginning instead.  Are you not seeing this?
-- 
Happy hacking
Petter Reinholdtsen

**Comment by steverweber** [comment]
seeking also not working well when using btfs + vlc


i never preformed in-depth tests... so might not be of much help
```
on slow wifi i did....
apt install -y btfs
#rm -rf ~/btfs
mkdir test
btfs https://archive.org/download/LoveNest/LoveNest_archive.torrent test
vlc test/LoveNest/keaton.love.nest.ogv
... seeking was kinda trashy.. i assume vlc is at fault
... however after file finishes downloading it works well.
also tried another player... totem seemed to work ok but still did crash sometimes.
```

**Comment by petterreinholdtsen** [comment]
Did you manage to reproduce this, or do you need more information on how to trigger the problem?

**Comment by johang** [comment]
There's probably a bug where I handle the events from libtorrent. Like events gets dropped or something.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> There's probably a bug where I handle the events from libtorrent. Like
> events gets dropped or something.

Aha.  I hope this mean it is easy to reproduce.

-- 
Happy hacking
Petter Reinholdtsen
