### ISSUE TITLE
Parse metadata failed (openSUSE Leap)

### ISSUE THREAD

**Issue by GriefNorth** [johang/vlc-bittorrent#24]
Hi, with build on openSUSE Leap 15, I have this error:
`Parse metadata failed: No such file or dir`
my --prefix=/usr --libdir=/usr/lib64/vlc/plugins

**Comment by johang** [comment]
Steps to reproduce?

**Comment by GriefNorth** [comment]
Install dependencies for building and build
```
git clone https://github.com/johang/vlc-bittorrent.git vlc-bittorrent
cd vlc-bittorrent
autoreconf -i
./configure --prefix=/usr --libdir=/usr/lib64/vlc/plugins/vlc-bittorrent
make
sudo make install
```
then download torrent file from tracker and run `vlc test.torrent`

**Comment by GriefNorth** [comment]
The same error.

**Comment by johang** [comment]
If you give me steps to reproduce this with Docker I can look at it.
