### ISSUE TITLE
Register on addons.videolan.org?

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#29]
The https://addons.videolan.org/ site contain a list of vlc plugins and extensions. Perhaps vlc-bittorrent should be registered there?

**Comment by petterreinholdtsen** [comment]
Hi @johang, did you have time to consider this proposal?

**Comment by johang** [comment]
Yeah, I guess I can register the plugin there, but I'm not interested in maintaining builds and packaging.

**Comment by petterreinholdtsen** [comment]
Did you succeed in registering the plugin?  I could not find it via https://addons.videolan.org/search/projectSearchText/bittorrent .

**Comment by johang** [comment]
I didn't register it. Don't see the point. This page is ranked very high by Google, so if you're looking for a plugin like this, you'll find it.
