### ISSUE TITLE
Download and load subtitle files of torrent

### ISSUE THREAD

**Issue by onny** [johang/vlc-bittorrent#30]
Hey,
this plugin is great, thank you for that!
I was missing the feature of auto loading subtitle files, which are also present in some torrent files. Other wise I have to manually download them elsewhere and load them into vlc.

Best regards,
Jonas

**Comment by petterreinholdtsen** [comment]
I have no idea how to do this myself.  Can you explain how can such subtitle files be recognized in the torrent?

**Comment by onny** [comment]
See for example this torrent file here https://webtorrent.io/torrents/sintel.torrent You can load the webtorrent file here https://btorrent.xyz There are the video file Sintel.mp4 and several subtitle files, for example Sintel.de.srt. These files are really small and easy to download with priority. Once they are downloaded from the torrent, they could be added to the available subtitles in the torrent video stream.
