### ISSUE TITLE
Contribute to VLC?

### ISSUE THREAD

**Issue by nullgat** [johang/vlc-bittorrent#33]
the ability to do peer to peer sharing with VLC seems like something the video lan organization would really support.

**Comment by johang** [comment]
I totally agree.

**Comment by petterreinholdtsen** [comment]
@nullgat If you want this to happen, you need to talk to the VLC developers and convince them to accept to include torrent support in their default build.  See #11 for a patch for the vlc source to support it, which has been lingering for years without getting anywhere closer to becoming part of upstream VLC.

**Comment by johang** [comment]
This is a complicated issue. At the end of the day it's a decision the VLC project have to make.
