### ISSUE TITLE
[Fedora 30] VLC crashes 

### ISSUE THREAD

**Issue by cociorbaandrei** [johang/vlc-bittorrent#35]
VLC crashes on fedora 30 when using the plugin. 

VLC_PLUGIN_PATH=/tmp/vlc/lib vlc  --no-plugins-cache torrent_file

/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = libtorrent::piece_picker::piece_pos; _Alloc = std::allocator<libtorrent::piece_picker::piece_pos>; std::vector<_Tp, _Alloc>::reference = libtorrent::piece_picker::piece_pos&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Thread 31 "vlc" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff95ff7700 (LWP 26992)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  0x00007ffff7dbee75 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7da9895 in __GI_abort () at abort.c:79
#2  0x00007fffea49d288 in  () at /lib64/libtorrent-rasterbar.so.9
#3  0x00007fffea5a7dbb in  () at /lib64/libtorrent-rasterbar.so.9
#4  0x00007fffea5ee6ed in void libtorrent::aux::fun_ret<bool>(bool&, bool&, libtorrent::condition_variable&, boost::asio::detail::posix_mutex&, boost::function<bool ()>) () at /lib64/libtorrent-rasterbar.so.9
#5  0x00007fffea5f19e5 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(bool&, bool&, libtorrent::condition_variable&, boost::asio::detail::posix_mutex&, boost::function<bool ()>), boost::_bi::list5<boost::reference_wrapper<bool>, boost::reference_wrapper<bool>, boost::reference_wrapper<libtorrent::condition_variable>, boost::reference_wrapper<boost::asio::detail::posix_mutex>, boost::_bi::value<boost::function<bool ()> > > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) () at /lib64/libtorrent-rasterbar.so.9
#6  0x00007fffea4d31ad in boost::asio::detail::scheduler::run(boost::system::error_code&) () at /lib64/libtorrent-rasterbar.so.9
#7  0x00007fffea5d3f52 in boost::asio::io_context::run() () at /lib64/libtorrent-rasterbar.so.9
#8  0x00007fffea4e35d4 in boost_asio_detail_posix_thread_function () at /lib64/libtorrent-rasterbar.so.9
#9  0x00007ffff7f5b5a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007ffff7e82303 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

**Comment by johang** [comment]
Looks like the crash is in libtorrent.

**Comment by johang** [comment]
I think this is same as #37.
