### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#39]
Hi.

I just noticed several changes since the last release this summer, as well as a build problem with the latest commit, and thought it best to as if a new release is planned soon.  I wonder if I should plan for an update in Debian before the freeze.

**Comment by johang** [comment]
Hi Petter. It would indeed be nice with a new release but there's a bug on master that causes a hang. I don't want to make a release before I have investigated it.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> Hi Petter. It would indeed be nice with a new release but there's a
> bug on master that causes a hang. I don't want to make a release
> before I have investigated it.

Right.  I hope you manage to investigate it soon, as the Debian freeze
for Bullseye is approaching fast.

<URL: https://tracker.debian.org/pkg/vlc-plugin-bittorrent >
-- 
Happy hacking
Petter Reinholdtsen

**Comment by johang** [comment]
I tagged v2.12 a few days ago.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> I tagged v2.12 a few days ago.

Thank you for the heads up.  I fetched the latest source and tried to
build it.  But the 'make check-TESTS' step got stuck.  Is this a known
problem:

make[4]: Leaving directory '/home/pere/src/debian/vlc-plugin-bittorrent-salsa/test'
make  check-TESTS
make[4]: Entering directory '/home/pere/src/debian/vlc-plugin-bittorrent-salsa/test'
make[5]: Entering directory '/home/pere/src/debian/vlc-plugin-bittorrent-salsa/test'
PASS: downloaddummy.test 1 # metadata flags.torrent
PASS: downloaddummy.test 2 # metadata nasa1.ogv.torrent
PASS: downloaddummy.test 3 # metadata nasa.torrent
PASS: downloaddummy.test 4 # metadata sweden.png.torrent
PASS: downloaddummy.test 5 # metadata magnet:?xt=urn:btih:18945a9300abfe4ff2442559bb08b8ddb357c16f&dn=flags
PASS: downloaddummy.test 6 # metadata magnet:?xt=urn:btih:8a32f3f6f3c9125da79e29c869122758004ee837&dn=nasa1.ogv
PASS: downloaddummy.test 7 # metadata magnet:?xt=urn:btih:6fa46c9a0bb4eecb837c25845d39c5324be66401&dn=nasa
PASS: downloaddummy.test 8 # metadata magnet:?xt=urn:btih:fce002e43ed1159f4612982ce8fcdb9d30e48f1e&dn=sweden.png
PASS: downloaddummy.test 9 # read flags.torrent
PASS: downloaddummy.test 10 # read nasa1.ogv.torrent
PASS: downloaddummy.test 11 # read nasa.torrent
PASS: downloaddummy.test 12 # read sweden.png.torrent
PASS: downloaddummy.test 13 # read magnet:?xt=urn:btih:18945a9300abfe4ff2442559bb08b8ddb357c16f&dn=flags
PASS: downloaddummy.test 14 # read magnet:?xt=urn:btih:8a32f3f6f3c9125da79e29c869122758004ee837&dn=nasa1.ogv
PASS: downloaddummy.test 15 # read magnet:?xt=urn:btih:6fa46c9a0bb4eecb837c25845d39c5324be66401&dn=nasa
PASS: downloaddummy.test 16 # read magnet:?xt=urn:btih:fce002e43ed1159f4612982ce8fcdb9d30e48f1e&dn=sweden.png
[here it got stuck for a long time]

Any idea how to avoid this?

Eventually, the tests failed

FAIL: vlcdummy.test 1 # metadata flags.torrent
FAIL: vlcdummy.test 2 # metadata nasa1.ogv.torrent
FAIL: vlcdummy.test 3 # metadata nasa.torrent
FAIL: vlcdummy.test 4 # metadata sweden.png.torrent
FAIL: vlcdummy.test 5 # metadata magnet:?xt=urn:btih:18945a9300abfe4ff2442559bb08b8ddb357c16f&dn=flags
FAIL: vlcdummy.test 6 # metadata magnet:?xt=urn:btih:8a32f3f6f3c9125da79e29c869122758004ee837&dn=nasa1.ogv
FAIL: vlcdummy.test 7 # metadata magnet:?xt=urn:btih:6fa46c9a0bb4eecb837c25845d39c5324be66401&dn=nasa
FAIL: vlcdummy.test 8 # metadata magnet:?xt=urn:btih:fce002e43ed1159f4612982ce8fcdb9d30e48f1e&dn=sweden.png
FAIL: vlcdummy.test 9 # data flags.torrent
FAIL: vlcdummy.test 10 # data nasa1.ogv.torrent
FAIL: vlcdummy.test 11 # data nasa.torrent
FAIL: vlcdummy.test 12 # data sweden.png.torrent
FAIL: vlcdummy.test 13 # data magnet:?xt=urn:btih:18945a9300abfe4ff2442559bb08b8ddb357c16f&dn=flags
FAIL: vlcdummy.test 14 # data magnet:?xt=urn:btih:8a32f3f6f3c9125da79e29c869122758004ee837&dn=nasa1.ogv
FAIL: vlcdummy.test 15 # data magnet:?xt=urn:btih:6fa46c9a0bb4eecb837c25845d39c5324be66401&dn=nasa
FAIL: vlcdummy.test 16 # data magnet:?xt=urn:btih:fce002e43ed1159f4612982ce8fcdb9d30e48f1e&dn=sweden.png
=====================================================
   vlc-plugin-bittorrent 2.12: test/test-suite.log
=====================================================

# TOTAL: 32
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  16
# XPASS: 0
# ERROR: 0
[...]

This was using libtorrent-rasterbar9 1.1.11-2 and libvlccore9
3.0.11-0+deb10u1 in Debian Buster.  When doing the same in Debian Sid,
the hang and failures do not happen.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by johang** [comment]
I don't see this hang in my tests. Do you have full log?

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> I don't see this hang in my tests. Do you have full log?

I tried four builds now, without being able to reproduce the hang.
Could it be that it only happen if I have a network issue locally?  I've
had unstable network here.

My first build hung with failing tests, the second one too, the next one
was build using unstable and worked fine, my forth was to upload a
source only to Debian experimental, and now the four failing tries
trying to reproduce the hang.  No idea what is needed to reproduce the
hang. :(

The new version is uploaded into Debian Experimental, did not dare to
upload to unstable and the next stable with the strange hang issue
somewhere in the code.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by johang** [comment]
The tests are fully local so network shouldn't matter. Would be interesting to see the contents of test/test-suite.log after a failed run.

**Comment by johang** [comment]
I don't fully understand the Debian build environment, but can you try to remove the line "export VLC_PLUGIN_PATH=$(pwd)/../src/.libs" from test/vlcdummy.test? Even if that works I think it's a bad idea to run those tests in the Debian build environment.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> I don't fully understand the Debian build environment, but can you try
> to remove the line "export VLC_PLUGIN_PATH=$(pwd)/../src/.libs" from
> test/vlcdummy.test? Even if that works I think it's a bad idea to run
> those tests in the Debian build environment.

I run the test during build to ensure no broken build end up in the
archive.  It is the only way to ensure broken architectures do not block
working architectures.

Why do you think it is a bad idea to run the tests in the build
environment?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by johang** [comment]
> Why do you think it is a bad idea to run the tests in the build environment?

Because the VLC tests doesn't work well if there's already a libaccess_bittorrent_plugin.so installed in the system.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> Because the VLC tests doesn't work well if there's already a
> libaccess_bittorrent_plugin.so installed in the system.

Aha.  Good thing that will not happen on the Debian autobuilders.  But
it could happen when a user try to build locally.  Hm.

I uploaded the new version to unstable and it is already in
Testing/Bullseye, as the hang do not seem to happen very often. :)

-- 
Happy hacking
Petter Reinholdtsen
