### ISSUE TITLE
Ubuntu - Qt: Session management error: Could not open network socket

### ISSUE THREAD

**Issue by LightC0de** [johang/vlc-bittorrent#40]
Ubuntu 20.04
I have problem 
Qt: Session management error: Could not open network socket

**Comment by johang** [comment]
I don't know what you mean. This project doesn't even use Qt.

**Comment by NizarPro** [comment]
i have the same error "Qt: Session management error: Could not open network socket"
ubuntu 20.04
i even tried with vpn with two different countries
