### ISSUE TITLE
can not make

### ISSUE THREAD

**Issue by sova32** [johang/vlc-bittorrent#43]
How can i install vlc-bittorrent in OpenSuse Thumbleweed?
vadiki@localhost:~/vlc-bittorrent> make
make: *** Не заданы цели и не найден make-файл.  Останов.
translate wiyh google from russian: No targets specified and no makefile found. Stop.
After rename Makefile.am to Makefile i have next error:
vadiki@localhost:~/vlc-bittorrent> make
Makefile:3: *** пропущен разделитель.  Останов.
translate:
missing separator. Stop.

**Comment by johang** [comment]
Follow the build instructions in README.md.

```
$ autoreconf -i
$ ./configure --prefix=/tmp/vlc
$ make
$ make install
```

**Comment by sova32** [comment]
Can you read?

vadiki@localhost:~> git clone https://github.com/johang/vlc-bittorrent.git vlc-bittorrent
Клонирование в «vlc-bittorrent»…
remote: Enumerating objects: 837, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 837 (delta 147), reused 175 (delta 87), pack-reused 584
Получение объектов: 100% (837/837), 1021.91 КиБ | 3.31 МиБ/с, готово.
Определение изменений: 100% (506/506), готово.
vadiki@localhost:~> cd vlc-bittorrent
vadiki@localhost:~/vlc-bittorrent> autoreconf -i
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:32: installing 'build-aux/compile'
configure.ac:32: installing 'build-aux/config.guess'
configure.ac:32: installing 'build-aux/config.sub'
configure.ac:14: installing 'build-aux/install-sh'
configure.ac:14: installing 'build-aux/missing'
configure.ac:7: installing 'build-aux/tap-driver.sh'
src/Makefile.am: installing 'build-aux/depcomp'
vadiki@localhost:~/vlc-bittorrent> ./configure --prefix=/tmp/vlc
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gawk... gawk
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for VLC_PLUGIN... no
configure: error: Package requirements (vlc-plugin >= 3.0.0) were not met:

Package 'vlc-plugin', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables VLC_PLUGIN_CFLAGS
and VLC_PLUGIN_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
vadiki@localhost:~/vlc-bittorrent> make
make: *** Не заданы цели и не найден make-файл.  Останов.
vadiki@localhost:~/vlc-bittorrent> 
translate with google from russian: No targets specified and no makefile found. Stop.

**Comment by johang** [comment]
> `configure: error: Package requirements (vlc-plugin >= 3.0.0) were not met:`

You're missing the vlc-plugin dependency.

**Comment by sova32** [comment]
vlc-plugin >= 3.0.0
where i can get it? it is not in the pacman and opensuse repository
Also i cannot install vlc from oficial website!:

An error occurred while initializing the software repository.
Details:
http-download.videolan.org-3a2ef1d7: [http-download.videolan.org-3a2ef1d7 | http: //download.videolan.org/openSUSE.org: / openSUSE: / Tumbleweed / dod /] No valid metadata found at the specified URL
History:
 - [http-download.videolan.org-3a2ef1d7 | http: //download.videolan.org/openSUSE.org: / openSUSE: / Tumbleweed / dod /] Unable to determine the type of repository.

Try again?

**Comment by johang** [comment]
You probably need vlc-devel.

**Comment by sova32** [comment]
thank you very much!
