### ISSUE TITLE
Torrent with multiple files

### ISSUE THREAD

**Issue by Mediashare** [johang/vlc-bittorrent#45]
When I come across a torrent that contains multiple video/audio files, they get lost in my playlist. Would it be possible to open a new window with the files or create a specific folder in the playlist?

I was also wondering where I can find the downloaded files on my disk?

**Comment by johang** [comment]
I don't understand your question about multifile torrents. Do you have an example torrent file that shows the problem?

FIles are downloaded to `config_GetUserDir(VLC_DOWNLOAD_DIR)`. The exact path depends on platform. It's overridable with `--bittorrent-download-path`.

**Comment by Mediashare** [comment]
> I don't understand your question about multifile torrents. Do you have an example torrent file that shows the problem?

I don't have the screenshots anymore but basically I have a big playlist, when I download the torrent, the files get hidden in the rest of the list.
I would like to see the new downloaded files in a new window, for more visibility.

> FIles are downloaded to `config_GetUserDir(VLC_DOWNLOAD_DIR)`. The exact path depends on platform. It's overridable with `--bittorrent-download-path`.

Thank's !
