### ISSUE TITLE
download directory

### ISSUE THREAD

**Issue by Spp595** [johang/vlc-bittorrent#49]
usually this plugin downloads a torrent to the download directory, but is it possible to change the directory?

**Comment by johang** [comment]
Use the `bittorrent-download-path` option.

**Comment by Spp595** [comment]
> Воспользуйтесь `bittorrent-download-path`опцией.

maybe I'm stupid, but I didn't understand what you mean)

**Comment by johang** [comment]
`vlc --bittorrent-download-path path/to/dir`
