### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by bphd** [johang/vlc-bittorrent#50]
If you know how can I get more informations?

It gets stuck at the loading bar in little window, despite using higly seeded torrents that works with other clients on the same host

**Comment by cbrunnkvist** [comment]
This project seems a little bit abandoned lately..? 

I warmly recommend trying [mafintosh/peerflix](https://github.com/mafintosh/peerflix) as an easy alternative (and inherently cross-platform) solution for the same use case.

**Comment by petterreinholdtsen** [comment]
I suspect you can see more information in the terminal where vlc output its stdout.  Which version and build are you using?

**Comment by bphd** [comment]
> This project seems a little bit abandoned lately..?
> 
> I warmly recommend trying [mafintosh/peerflix](https://github.com/mafintosh/peerflix) as an easy alternative (and inherently cross-platform) solution for the same use case.

Yeah a lot of solutions possible, even the historical one popcorn-time, but I liked the VLC-Plugin concept here. I better just use qBit otherwise

**Comment by johang** [comment]
Works fine.

**Comment by cbrunnkvist** [comment]
Okay if you say so. 😵 

In the meantime I guess `brew install webtorrent` will suffice for me instead. Thanks.
